name: test
on: [push]
jobs:
  build:
    name: Test Guix installation
    runs-on: ubuntu-latest
    steps:
      - name: Guix cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/guix
            /var/cache/guix/
          # use a key that (almost) never matches
          key: guix-cache-${{ github.sha }}
          restore-keys: |
            guix-cache-
      # Cannot use a cache for /gnu/store, since restore fails
      - name: Install Guix
        uses: PromyLOPh/guix-install-action@v1
      - name: Ensure no locale warning
        run: test -z "$(guix --version 2>&1 >/dev/null)"
      - name: Install build tools
        run: guix install openjdk@17:jdk maven
      - uses: actions/checkout@v4
        with:
          repository: 'BaseXdb/basex'
          ref: '12.0'
      - name: maven
        shell: bash
        run: mvn compile && mvn package && mvn install
        env: 
          MAVEN_OPTS: "--add-opens java.base/java.lang=ALL-UNNAMED"

          
